resourcePath: /auth
apis: 

- path: /api/auth/logout
  operations:

  - httpMethod: GET
    nickname: logout

- path: /api/auth/fb/{token}/{id}

  operations:

  - httpMethod: GET
    nickname: fb
    parameters:

    - name: token
      dataType: string
      paramType: path
      required: true
      description: "Access Token from Facebook"

    - name: id
      dataType: int
      paramType: path
      required: true
      description: "Facebook profile id"